
version: "3.7"

services:
  server:
    container_name: task2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8080:8080
    volumes:
        - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5